CTA updates
Banyan-Labs/time-tracking-app-board pull request #17
Opened 2021-09-02 15:22 UTC by AshleyThomas87

2021-09-02 16:43 UTC, jmclain-banyan commented on src/Components/CTA/CTA.jsx
> +}
A couple of things here, 

`e.preventDefault()` will throw an error because we did not capture `e` in our parameters in the definition of the function. Also it is not necessary for prevent default here.

in general we should not leave console.log in our code

let's rename this function to `handleClick` and make this a redirect link using a hook from `react-router-dom` package.
[Check out this link for more info on `useHistory` hook](https://reactrouter.com/web/api/Hooks)

the redirect route should be `/sign-up`

2021-09-02 16:55 UTC, jmclain-banyan requested changes

2021-09-02 16:55 UTC, jmclain-banyan commented on src/Components/CTA/CTA.jsx
> +        </section>
instead of using a `<section>` tag, let's create a styled component to contain its children and apply some style to center its content on the screen

2021-09-02 16:55 UTC, jmclain-banyan commented on src/Components/CTA/style.js
> +`;
Overall looks good

related to my comment about the `<section>` tag

we can create a styled component `Container = styled.section` and give it a couple properties to center its content, also maybe add some padding to its area as well

2021-09-02 16:56 UTC, jmclain-banyan commented on src/Components/CTA/CTA.jsx
> +}
also let's rename this file to `index.jsx`

2021-09-03 16:11 UTC, AshleyThomas87 commented
Made changes and ready for review. Thank you for the directions. They were easy to understand and follow.

2021-09-03 17:01 UTC, jmclain-banyan approved these changes

2021-09-03 17:02 UTC, merged