Ttab 25
Banyan-Labs/time-tracking-app-board pull request #24
Opened 2021-09-08 16:04 UTC by AshleyThomas87

footer updates
<img width="960" alt="footer" src="https://user-images.githubusercontent.com/77860087/132544565-8d65df8f-97c1-4a71-8fda-1f778f00d394.PNG">

2021-09-08 20:12 UTC, jmclain-banyan commented on src/Components/Footer/style.jsx
> +  background: #030305;
lets grab this color from our colors object in `src/styles/colors.js`

2021-09-08 20:13 UTC, jmclain-banyan commented on src/Components/Footer/style.jsx
> +  font-size: clamp(18px, 4vw, 18px);
for the font-size lets set the max to 22px

2021-09-08 20:13 UTC, jmclain-banyan commented on src/Components/Footer/style.jsx
> +  font-size: clamp(18px, 4vw, 18px);
for the font-size lets set the min to 14px and max 22px

2021-09-08 20:14 UTC, jmclain-banyan requested changes
overall looks good, just a couple small changes

2021-09-10 06:54 UTC, AshleyThomas87 commented
made new updates

2021-09-10 16:56 UTC, jmclain-banyan approved these changes

2021-09-10 16:56 UTC, merged