Ttab 26
Banyan-Labs/time-tracking-app-board pull request #25
Opened 2021-09-08 16:24 UTC by AshleyThomas87

Navbar positioning sticky to stay and scroll
<img width="684" alt="Navbar" src="https://user-images.githubusercontent.com/77860087/132547667-8922f292-e3d7-4b0b-84bd-89c9e0c4bb36.PNG">

2021-09-08 20:17 UTC, jmclain-banyan requested changes

2021-09-08 20:17 UTC, jmclain-banyan commented on src/Components/Navbar/style.js
> +  position: sticky;
in order for `position: sticky` to know where to stick we need to have a `top: 0` property

2021-09-09 15:22 UTC, AshleyThomas87 commented
updated navbar so its sticky and at the top.
<img width="374" alt="sticky" src="https://user-images.githubusercontent.com/77860087/132714668-273f1407-39f6-4be5-8ccb-44534a5a3d8a.PNG">

2021-09-09 17:21 UTC, jmclain-banyan approved these changes

2021-09-09 17:21 UTC, merged